/**
* 
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AlertMethodEnum
import org.openapitools.client.models.AlertTypeEnum
import org.openapitools.client.models.RemoteControlCommandAlertAlertSubtypeEnum

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param alertSubtype 
 * @param alertType 
 * @param color 
 * @param icon 
 * @param description 
 * @param title 
 * @param alertMethod 
 * @param seen 
 */

data class RemoteControlCommandAlertRequest (
    @Json(name = "alert_subtype")
    val alertSubtype: RemoteControlCommandAlertAlertSubtypeEnum,
    @Json(name = "alert_type")
    val alertType: AlertTypeEnum,
    @Json(name = "color")
    val color: kotlin.String,
    @Json(name = "icon")
    val icon: kotlin.String,
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "title")
    val title: kotlin.String,
    @Json(name = "alert_method")
    val alertMethod: AlertMethodEnum? = null,
    @Json(name = "seen")
    val seen: kotlin.Boolean? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

