# Generated by Django 3.2.9 on 2021-12-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0007_alter_release_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="checksum",
        ),
        migrations.RemoveField(
            model_name="release",
            name="checksum_url",
        ),
        migrations.RemoveField(
            model_name="release",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="release",
            name="manifest_url",
        ),
        migrations.RemoveField(
            model_name="release",
            name="sig_url",
        ),
        migrations.AddField(
            model_name="release",
            name="zip_url",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="release",
            name="variant",
            field=models.CharField(
                choices=[
                    ("base_desktop", "Customizable Desktop Edition"),
                    ("base_slim", "Slim Headless Edition"),
                    ("octoprint_desktop", "OctoPrint Desktop Edition"),
                    ("octoprint_slim", "OctoPrint Slim Edition"),
                ],
                max_length=32,
            ),
        ),
    ]
