version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: "us.gcr.io/${GCP_PROJECT}/print_nanny_webapp:${GIT_SHA}"
    ports:
      - 8000:8000
    command: /start
