version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: print_nanny_webapp_production_django
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: print_nanny_webapp_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  redis:

    build:
      context: .
      dockerfile: ./compose/production/redis/Dockerfile
    container_name: redis

  # celeryworker:
  #   <<: *django
  #   ports: []
  #   image: print_nanny_webapp_production_celeryworker
  #   command: /start-celeryworker

  # celerybeat:
  #   <<: *django
  #   ports: []
  #   image: print_nanny_webapp_production_celerybeat
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   ports: []
  #   image: print_nanny_webapp_production_flower
  #   command: /start-flower

  
