version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_file_data: {}
  local_octoprint_data: {}
  local_nsc_data: {}
services:
  janus:
    hostname: janus
    image: bitsyai/janus:1.0.4
    container_name: printnanny_janus
    ports:
      - "8188:8188"
      - "7188:7188"
      - "7088:7088"
      - "8088:8088"
      - "5000-5100:5000-5100/udp"
    env_file:
      - ./.envs/.local/.janus
    volumes:
      - ./compose/local/janus/etc:/etc/janus
  django: &django # enables use of pdb
    hostname: django
    # network_mode: "host"
    image: bitsyai/printnanny-webapp:${GIT_BRANCH}
    container_name: printnanny_webapp_django
    depends_on:
      - postgres
      - nats
      - janus
      - mailhog
    volumes:
      - .:/app:z
      - local_file_data:/tmp:z
      # prevent host machine .venv and node_modules from being included in container
      # idea from: https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      - /app/node_modules
      - /app/.venv
      - local_nsc_data:/var/lib/nats/nsc:z
    environment:
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      NKEYS_PATH: /var/lib/nats/nsc/keys
      NSC_HOME: /var/lib/nats/nsc
      NSC_STORE: /var/lib/nats/nsc/stores
      STRIPE_TEST_PUBLIC_KEY: $STRIPE_TEST_PUBLIC_KEY}
      STRIPE_TEST_SECRET_KEY: ${STRIPE_TEST_SECRET_KEY}
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
      - "8001:8001"

    command:
      - /start
  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: printnanny_webapp_local_mailhog
    ports:
      - "8025:8025"

  firehose: &firehose
    hostname: firehose
    depends_on:
      - postgres
      - nats
    image: bitsyai/printnanny-webapp:${GIT_BRANCH}
    container_name: printnanny_webapp_firehose
    environment:
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      NKEYS_PATH: /var/lib/nats/nsc/keys
      NSC_HOME: /var/lib/nats/nsc
      NSC_STORE: /var/lib/nats/nsc/stores
      DJANGO_SETTINGS_MODULE: config.settings.local
      STRIPE_TEST_PUBLIC_KEY: ${STRIPE_TEST_PUBLIC_KEY}
      STRIPE_TEST_SECRET_KEY: ${STRIPE_TEST_SECRET_KEY}
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    volumes:
      - .:/app:z
      - local_nsc_data:/var/lib/nats/nsc:z

    command:
      - python
      - -m
      - print_nanny_webapp.events.streams.firehose
  postgres:
    hostname: postgres
    image: postgres:12.3
    container_name: printnanny_webapp_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    # network_mode: "host"
    hostname: redis
    build:
      context: .
      dockerfile: ./compose/local/redis/Dockerfile
    container_name: printnanny_webapp_redis
    ports:
      - "6379:6379"

  nats:
    hostname: nats
    image: nats:2.8-alpine
    container_name: printnanny_webapp_nats
    volumes:
      - .nats/:/etc/nats
    command:
      - -c
      - /etc/nats/nats-server.conf
      - --name
      - localnats
    ports:
      - "4222:4222"
      - "8443:8443"
