"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class VideoRenderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PRINT_SESSION_FIELD_NUMBER: builtins.int
    PRINT_SESSION_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    OCTOPRINT_DEVICE_ID_FIELD_NUMBER: builtins.int
    CLOUDIOT_DEVICE_NUM_ID_FIELD_NUMBER: builtins.int
    TS_FIELD_NUMBER: builtins.int
    CDN_OUTPUT_PATH_FIELD_NUMBER: builtins.int
    PRINT_SESSION_DATESEGMENT_FIELD_NUMBER: builtins.int
    print_session: typing.Text = ...
    print_session_id: builtins.int = ...
    user_id: builtins.int = ...
    octoprint_device_id: builtins.int = ...
    cloudiot_device_num_id: builtins.int = ...
    ts: builtins.float = ...
    cdn_output_path: typing.Text = ...
    print_session_datesegment: typing.Text = ...

    def __init__(self,
        *,
        print_session : typing.Text = ...,
        print_session_id : builtins.int = ...,
        user_id : builtins.int = ...,
        octoprint_device_id : builtins.int = ...,
        cloudiot_device_num_id : builtins.int = ...,
        ts : builtins.float = ...,
        cdn_output_path : typing.Text = ...,
        print_session_datesegment : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"cdn_output_path",b"cdn_output_path",u"cloudiot_device_num_id",b"cloudiot_device_num_id",u"octoprint_device_id",b"octoprint_device_id",u"print_session",b"print_session",u"print_session_datesegment",b"print_session_datesegment",u"print_session_id",b"print_session_id",u"ts",b"ts",u"user_id",b"user_id"]) -> None: ...
global___VideoRenderRequest = VideoRenderRequest
