/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertRequest {
    #[serde(rename = "octoprint_device", skip_serializing_if = "Option::is_none")]
    pub octoprint_device: Option<i32>,
    #[serde(rename = "event_type", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<Box<crate::models::AlertEventTypeEnum>>,
    #[serde(rename = "seen", skip_serializing_if = "Option::is_none")]
    pub seen: Option<bool>,
    #[serde(rename = "sent", skip_serializing_if = "Option::is_none")]
    pub sent: Option<bool>,
}

impl AlertRequest {
    pub fn new() -> AlertRequest {
        AlertRequest {
            octoprint_device: NoneSome(,
            event_type: NoneSome(,
            seen: None,
            sent: None,
        }
    }
}


