/*
 * printnanny-api-client
 *
 * Official API client library forprintnanny.ai print-nanny.com
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: leigh@printnanny.ai
 * Generated by: https://openapi-generator.tech
 */

/// AlertBulkResponse : Serializer used in POST /api/alerts/seen and POST /api/alerts/dismiss requests



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AlertBulkResponse {
    #[serde(rename = "received")]
    pub received: i32,
    #[serde(rename = "updated")]
    pub updated: i32,
}

impl AlertBulkResponse {
    /// Serializer used in POST /api/alerts/seen and POST /api/alerts/dismiss requests
    pub fn new(received: i32, updated: i32) -> AlertBulkResponse {
        AlertBulkResponse {
            received,
            updated,
        }
    }
}


