/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceIdentity {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<String>,
    #[serde(rename = "created_dt", skip_serializing_if = "Option::is_none")]
    pub created_dt: Option<String>,
    #[serde(rename = "updated_dt", skip_serializing_if = "Option::is_none")]
    pub updated_dt: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<i32>,
    #[serde(rename = "hostname")]
    pub hostname: String,
    #[serde(rename = "public_key", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
    #[serde(rename = "fingerprint", skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<String>,
    #[serde(rename = "cloudiot_device", skip_serializing_if = "Option::is_none")]
    pub cloudiot_device: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "cloudiot_device_name", skip_serializing_if = "Option::is_none")]
    pub cloudiot_device_name: Option<String>,
    #[serde(rename = "cloudiot_device_path", skip_serializing_if = "Option::is_none")]
    pub cloudiot_device_path: Option<String>,
    #[serde(rename = "cloudiot_device_num_id", skip_serializing_if = "Option::is_none")]
    pub cloudiot_device_num_id: Option<i32>,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "cpu_flags")]
    pub cpu_flags: String,
    #[serde(rename = "hardware", skip_serializing_if = "Option::is_none")]
    pub hardware: Option<String>,
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "serial")]
    pub serial: String,
    #[serde(rename = "cores")]
    pub cores: i32,
    #[serde(rename = "ram")]
    pub ram: i32,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "private_key", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<String>,
    #[serde(rename = "private_key_checksum", skip_serializing_if = "Option::is_none")]
    pub private_key_checksum: Option<String>,
    #[serde(rename = "public_key_checksum")]
    pub public_key_checksum: String,
    #[serde(rename = "cloudiot_device_configs", skip_serializing_if = "Option::is_none")]
    pub cloudiot_device_configs: Option<String>,
    #[serde(rename = "ca_certs")]
    pub ca_certs: ::std::collections::HashMap<String, String>,
    #[serde(rename = "manage_url", skip_serializing_if = "Option::is_none")]
    pub manage_url: Option<String>,
}

impl DeviceIdentity {
    pub fn new(hostname: String, platform: String, cpu_flags: String, model: String, serial: String, cores: i32, ram: i32, public_key_checksum: String, ca_certs: ::std::collections::HashMap<String, String>) -> DeviceIdentity {
        DeviceIdentity {
            id: None,
            deleted: None,
            created_dt: None,
            updated_dt: None,
            user: None,
            hostname,
            public_key: None,
            fingerprint: None,
            cloudiot_device: None,
            cloudiot_device_name: None,
            cloudiot_device_path: None,
            cloudiot_device_num_id: None,
            platform,
            cpu_flags,
            hardware: None,
            revision: None,
            model,
            serial,
            cores,
            ram,
            url: None,
            private_key: None,
            private_key_checksum: None,
            public_key_checksum,
            cloudiot_device_configs: None,
            ca_certs,
            manage_url: None,
        }
    }
}


