/*
 * printnanny-api-client
 *
 * Official API client library forprintnanny.ai print-nanny.com
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: leigh@printnanny.ai
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventSource {
    #[serde(rename = "octoprint")]
    Octoprint,
    #[serde(rename = "printnanny_os")]
    PrintnannyOs,
    #[serde(rename = "printnanny_webapp")]
    PrintnannyWebapp,
    #[serde(rename = "mainsail")]
    Mainsail,

}

impl ToString for EventSource {
    fn to_string(&self) -> String {
        match self {
            Self::Octoprint => String::from("octoprint"),
            Self::PrintnannyOs => String::from("printnanny_os"),
            Self::PrintnannyWebapp => String::from("printnanny_webapp"),
            Self::Mainsail => String::from("mainsail"),
        }
    }
}

impl Default for EventSource {
    fn default() -> EventSource {
        Self::Octoprint
    }
}




