/*
 * printnanny-api-client
 *
 * Official API client library for print-nanny.com
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: leigh@print-nanny.com
 * Generated by: https://openapi-generator.tech
 */

/// License : Deserialize data/license info into /opt/printnanny during License Activation



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct License {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "tokens")]
    pub tokens: Box<crate::models::LicenseTokens>,
    #[serde(rename = "activated", skip_serializing_if = "Option::is_none")]
    pub activated: Option<bool>,
    #[serde(rename = "public_key")]
    pub public_key: String,
    #[serde(rename = "fingerprint")]
    pub fingerprint: String,
    #[serde(rename = "created_dt")]
    pub created_dt: String,
    #[serde(rename = "device")]
    pub device: i32,
}

impl License {
    /// Deserialize data/license info into /opt/printnanny during License Activation
    pub fn new(id: i32, tokens: crate::models::LicenseTokens, public_key: String, fingerprint: String, created_dt: String, device: i32) -> License {
        License {
            id,
            tokens: Box::new(tokens),
            activated: None,
            public_key,
            fingerprint,
            created_dt,
            device,
        }
    }
}


