/*
 * printnanny-api-client
 *
 * Official API client library for print-nanny.com
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: leigh@print-nanny.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MonitorStopTaskRequest {
    #[serde(rename = "janus_media_stream")]
    pub janus_media_stream: i32,
}

impl MonitorStopTaskRequest {
    pub fn new(janus_media_stream: i32) -> MonitorStopTaskRequest {
        MonitorStopTaskRequest {
            janus_media_stream,
        }
    }
}


