/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReleaseRequest {
    #[serde(rename = "ansible_extra_vars")]
    pub ansible_extra_vars: Box<crate::models::AnsibleExtraVarsRequest>,
    #[serde(rename = "release_channel", skip_serializing_if = "Option::is_none")]
    pub release_channel: Option<crate::models::ReleaseChannelEnum>,
}

impl ReleaseRequest {
    pub fn new(ansible_extra_vars: crate::models::AnsibleExtraVarsRequest) -> ReleaseRequest {
        ReleaseRequest {
            ansible_extra_vars: Box::new(ansible_extra_vars),
            release_channel: None,
        }
    }
}


