/*
 * printnanny-api-client
 *
 * Official API client library for print-nanny.com
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: leigh@print-nanny.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SystemTaskStatusRequest {
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[serde(rename = "wiki_url", skip_serializing_if = "Option::is_none")]
    pub wiki_url: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::StatusEnum>,
    #[serde(rename = "system_task")]
    pub system_task: i32,
}

impl SystemTaskStatusRequest {
    pub fn new(system_task: i32) -> SystemTaskStatusRequest {
        SystemTaskStatusRequest {
            detail: None,
            wiki_url: None,
            status: None,
            system_task,
        }
    }
}


