/*
 * printnanny-api-client
 *
 * Official API client library for print-nanny.com
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: leigh@print-nanny.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SystemTaskType {
    #[serde(rename = "activate_license")]
    ActivateLicense,
    #[serde(rename = "software_update")]
    SoftwareUpdate,

}

impl ToString for SystemTaskType {
    fn to_string(&self) -> String {
        match self {
            Self::ActivateLicense => String::from("activate_license"),
            Self::SoftwareUpdate => String::from("software_update"),
        }
    }
}

impl Default for SystemTaskType {
    fn default() -> SystemTaskType {
        Self::ActivateLicense
    }
}




