/*
 * printnanny-api-client
 *
 * Official API client library for print-nanny.com
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: leigh@print-nanny.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TelemetryEventEventTypeEnum {
    #[serde(rename = "plugin_octoprint_nanny_monitoring_start")]
    PluginOctoprintNannyMonitoringStart,
    #[serde(rename = "plugin_octoprint_nanny_monitoring_stop")]
    PluginOctoprintNannyMonitoringStop,
    #[serde(rename = "plugin_octoprint_nanny_monitoring_reset")]
    PluginOctoprintNannyMonitoringReset,
    #[serde(rename = "plugin_octoprint_nanny_device_register_start")]
    PluginOctoprintNannyDeviceRegisterStart,
    #[serde(rename = "plugin_octoprint_nanny_device_register_done")]
    PluginOctoprintNannyDeviceRegisterDone,
    #[serde(rename = "plugin_octoprint_nanny_device_register_failed")]
    PluginOctoprintNannyDeviceRegisterFailed,
    #[serde(rename = "plugin_octoprint_nanny_device_reset")]
    PluginOctoprintNannyDeviceReset,
    #[serde(rename = "plugin_octoprint_nanny_printer_profile_sync_start")]
    PluginOctoprintNannyPrinterProfileSyncStart,
    #[serde(rename = "plugin_octoprint_nanny_printer_profile_sync_done")]
    PluginOctoprintNannyPrinterProfileSyncDone,
    #[serde(rename = "plugin_octoprint_nanny_printer_profile_sync_failed")]
    PluginOctoprintNannyPrinterProfileSyncFailed,
    #[serde(rename = "plugin_octoprint_nanny_connect_test_rest_api")]
    PluginOctoprintNannyConnectTestRestApi,
    #[serde(rename = "plugin_octoprint_nanny_connect_test_rest_api_failed")]
    PluginOctoprintNannyConnectTestRestApiFailed,
    #[serde(rename = "plugin_octoprint_nanny_connect_test_rest_api_success")]
    PluginOctoprintNannyConnectTestRestApiSuccess,
    #[serde(rename = "plugin_octoprint_nanny_connect_test_mqtt_ping")]
    PluginOctoprintNannyConnectTestMqttPing,
    #[serde(rename = "plugin_octoprint_nanny_connect_test_mqtt_ping_failed")]
    PluginOctoprintNannyConnectTestMqttPingFailed,
    #[serde(rename = "plugin_octoprint_nanny_connect_test_mqtt_ping_success")]
    PluginOctoprintNannyConnectTestMqttPingSuccess,
    #[serde(rename = "plugin_octoprint_nanny_connect_test_mqtt_pong")]
    PluginOctoprintNannyConnectTestMqttPong,
    #[serde(rename = "plugin_octoprint_nanny_connect_test_mqtt_pong_failed")]
    PluginOctoprintNannyConnectTestMqttPongFailed,
    #[serde(rename = "plugin_octoprint_nanny_connect_test_mqtt_pong_success")]
    PluginOctoprintNannyConnectTestMqttPongSuccess,
    #[serde(rename = "connect_test_noop")]
    ConnectTestNoop,
    #[serde(rename = "ClientAuthed")]
    ClientAuthed,
    #[serde(rename = "ClientClosed")]
    ClientClosed,
    #[serde(rename = "ClientDeauthed")]
    ClientDeauthed,
    #[serde(rename = "ClientOpened")]
    ClientOpened,
    #[serde(rename = "SettingsUpdated")]
    SettingsUpdated,
    #[serde(rename = "UserLoggedIn")]
    UserLoggedIn,
    #[serde(rename = "UserLoggedOut")]
    UserLoggedOut,
    #[serde(rename = "FileAdded")]
    FileAdded,
    #[serde(rename = "FileRemoved")]
    FileRemoved,
    #[serde(rename = "FolderAdded")]
    FolderAdded,
    #[serde(rename = "FolderRemoved")]
    FolderRemoved,
    #[serde(rename = "TransferDone")]
    TransferDone,
    #[serde(rename = "TransferFailed")]
    TransferFailed,
    #[serde(rename = "TransferStarted")]
    TransferStarted,
    #[serde(rename = "UpdatedFiles")]
    UpdatedFiles,
    #[serde(rename = "Upload")]
    Upload,
    #[serde(rename = "CaptureDone")]
    CaptureDone,
    #[serde(rename = "CaptureFailed")]
    CaptureFailed,
    #[serde(rename = "CaptureStart")]
    CaptureStart,
    #[serde(rename = "MovieDone")]
    MovieDone,
    #[serde(rename = "MovieFailed")]
    MovieFailed,
    #[serde(rename = "MovieRendering")]
    MovieRendering,
    #[serde(rename = "PostRollEnd")]
    PostRollEnd,
    #[serde(rename = "PostRollStart")]
    PostRollStart,
    #[serde(rename = "SlicingCancelled")]
    SlicingCancelled,
    #[serde(rename = "SlicingDone")]
    SlicingDone,
    #[serde(rename = "SlicingFailed")]
    SlicingFailed,
    #[serde(rename = "SlicingProfileAdded")]
    SlicingProfileAdded,
    #[serde(rename = "SlicingProfileDeleted")]
    SlicingProfileDeleted,
    #[serde(rename = "SlicingProfileModified")]
    SlicingProfileModified,
    #[serde(rename = "SlicingStarted")]
    SlicingStarted,
    #[serde(rename = "Connected")]
    Connected,
    #[serde(rename = "Disconnected")]
    Disconnected,
    #[serde(rename = "PrinterReset")]
    PrinterReset,
    #[serde(rename = "FirmwareData")]
    FirmwareData,
    #[serde(rename = "PrinterProfileAdded")]
    PrinterProfileAdded,
    #[serde(rename = "PrinterProfileDeleted")]
    PrinterProfileDeleted,
    #[serde(rename = "PrinterProfileModified")]
    PrinterProfileModified,
    #[serde(rename = "PrintProgress")]
    PrintProgress,
    #[serde(rename = "plugin_pi_support_throttle_state")]
    PluginPiSupportThrottleState,
    #[serde(rename = "Shutdown")]
    Shutdown,
    #[serde(rename = "Startup")]
    Startup,
    #[serde(rename = "remote_command_received")]
    RemoteCommandReceived,
    #[serde(rename = "remote_command_failed")]
    RemoteCommandFailed,
    #[serde(rename = "remote_command_success")]
    RemoteCommandSuccess,
    #[serde(rename = "PrintCancelled")]
    PrintCancelled,
    #[serde(rename = "PrintCancelling")]
    PrintCancelling,
    #[serde(rename = "PrintDone")]
    PrintDone,
    #[serde(rename = "PrintFailed")]
    PrintFailed,
    #[serde(rename = "PrintPaused")]
    PrintPaused,
    #[serde(rename = "PrintResumed")]
    PrintResumed,
    #[serde(rename = "PrintStarted")]
    PrintStarted,
    #[serde(rename = "PrinterStateChanged")]
    PrinterStateChanged,

}

impl ToString for TelemetryEventEventTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::PluginOctoprintNannyMonitoringStart => String::from("plugin_octoprint_nanny_monitoring_start"),
            Self::PluginOctoprintNannyMonitoringStop => String::from("plugin_octoprint_nanny_monitoring_stop"),
            Self::PluginOctoprintNannyMonitoringReset => String::from("plugin_octoprint_nanny_monitoring_reset"),
            Self::PluginOctoprintNannyDeviceRegisterStart => String::from("plugin_octoprint_nanny_device_register_start"),
            Self::PluginOctoprintNannyDeviceRegisterDone => String::from("plugin_octoprint_nanny_device_register_done"),
            Self::PluginOctoprintNannyDeviceRegisterFailed => String::from("plugin_octoprint_nanny_device_register_failed"),
            Self::PluginOctoprintNannyDeviceReset => String::from("plugin_octoprint_nanny_device_reset"),
            Self::PluginOctoprintNannyPrinterProfileSyncStart => String::from("plugin_octoprint_nanny_printer_profile_sync_start"),
            Self::PluginOctoprintNannyPrinterProfileSyncDone => String::from("plugin_octoprint_nanny_printer_profile_sync_done"),
            Self::PluginOctoprintNannyPrinterProfileSyncFailed => String::from("plugin_octoprint_nanny_printer_profile_sync_failed"),
            Self::PluginOctoprintNannyConnectTestRestApi => String::from("plugin_octoprint_nanny_connect_test_rest_api"),
            Self::PluginOctoprintNannyConnectTestRestApiFailed => String::from("plugin_octoprint_nanny_connect_test_rest_api_failed"),
            Self::PluginOctoprintNannyConnectTestRestApiSuccess => String::from("plugin_octoprint_nanny_connect_test_rest_api_success"),
            Self::PluginOctoprintNannyConnectTestMqttPing => String::from("plugin_octoprint_nanny_connect_test_mqtt_ping"),
            Self::PluginOctoprintNannyConnectTestMqttPingFailed => String::from("plugin_octoprint_nanny_connect_test_mqtt_ping_failed"),
            Self::PluginOctoprintNannyConnectTestMqttPingSuccess => String::from("plugin_octoprint_nanny_connect_test_mqtt_ping_success"),
            Self::PluginOctoprintNannyConnectTestMqttPong => String::from("plugin_octoprint_nanny_connect_test_mqtt_pong"),
            Self::PluginOctoprintNannyConnectTestMqttPongFailed => String::from("plugin_octoprint_nanny_connect_test_mqtt_pong_failed"),
            Self::PluginOctoprintNannyConnectTestMqttPongSuccess => String::from("plugin_octoprint_nanny_connect_test_mqtt_pong_success"),
            Self::ConnectTestNoop => String::from("connect_test_noop"),
            Self::ClientAuthed => String::from("ClientAuthed"),
            Self::ClientClosed => String::from("ClientClosed"),
            Self::ClientDeauthed => String::from("ClientDeauthed"),
            Self::ClientOpened => String::from("ClientOpened"),
            Self::SettingsUpdated => String::from("SettingsUpdated"),
            Self::UserLoggedIn => String::from("UserLoggedIn"),
            Self::UserLoggedOut => String::from("UserLoggedOut"),
            Self::FileAdded => String::from("FileAdded"),
            Self::FileRemoved => String::from("FileRemoved"),
            Self::FolderAdded => String::from("FolderAdded"),
            Self::FolderRemoved => String::from("FolderRemoved"),
            Self::TransferDone => String::from("TransferDone"),
            Self::TransferFailed => String::from("TransferFailed"),
            Self::TransferStarted => String::from("TransferStarted"),
            Self::UpdatedFiles => String::from("UpdatedFiles"),
            Self::Upload => String::from("Upload"),
            Self::CaptureDone => String::from("CaptureDone"),
            Self::CaptureFailed => String::from("CaptureFailed"),
            Self::CaptureStart => String::from("CaptureStart"),
            Self::MovieDone => String::from("MovieDone"),
            Self::MovieFailed => String::from("MovieFailed"),
            Self::MovieRendering => String::from("MovieRendering"),
            Self::PostRollEnd => String::from("PostRollEnd"),
            Self::PostRollStart => String::from("PostRollStart"),
            Self::SlicingCancelled => String::from("SlicingCancelled"),
            Self::SlicingDone => String::from("SlicingDone"),
            Self::SlicingFailed => String::from("SlicingFailed"),
            Self::SlicingProfileAdded => String::from("SlicingProfileAdded"),
            Self::SlicingProfileDeleted => String::from("SlicingProfileDeleted"),
            Self::SlicingProfileModified => String::from("SlicingProfileModified"),
            Self::SlicingStarted => String::from("SlicingStarted"),
            Self::Connected => String::from("Connected"),
            Self::Disconnected => String::from("Disconnected"),
            Self::PrinterReset => String::from("PrinterReset"),
            Self::FirmwareData => String::from("FirmwareData"),
            Self::PrinterProfileAdded => String::from("PrinterProfileAdded"),
            Self::PrinterProfileDeleted => String::from("PrinterProfileDeleted"),
            Self::PrinterProfileModified => String::from("PrinterProfileModified"),
            Self::PrintProgress => String::from("PrintProgress"),
            Self::PluginPiSupportThrottleState => String::from("plugin_pi_support_throttle_state"),
            Self::Shutdown => String::from("Shutdown"),
            Self::Startup => String::from("Startup"),
            Self::RemoteCommandReceived => String::from("remote_command_received"),
            Self::RemoteCommandFailed => String::from("remote_command_failed"),
            Self::RemoteCommandSuccess => String::from("remote_command_success"),
            Self::PrintCancelled => String::from("PrintCancelled"),
            Self::PrintCancelling => String::from("PrintCancelling"),
            Self::PrintDone => String::from("PrintDone"),
            Self::PrintFailed => String::from("PrintFailed"),
            Self::PrintPaused => String::from("PrintPaused"),
            Self::PrintResumed => String::from("PrintResumed"),
            Self::PrintStarted => String::from("PrintStarted"),
            Self::PrinterStateChanged => String::from("PrinterStateChanged"),
        }
    }
}

impl Default for TelemetryEventEventTypeEnum {
    fn default() -> TelemetryEventEventTypeEnum {
        Self::PluginOctoprintNannyMonitoringStart
    }
}




