/*
 * printnanny-api-client
 *
 * Official API client library for print-nanny.com
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: leigh@print-nanny.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebRtcEventRequest {
    #[serde(rename = "source")]
    pub source: crate::models::EventSource,
    #[serde(rename = "event_type")]
    pub event_type: crate::models::WebRtcEventType,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "device")]
    pub device: i32,
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<i32>,
}

impl WebRtcEventRequest {
    pub fn new(source: crate::models::EventSource, event_type: crate::models::WebRtcEventType, device: i32) -> WebRtcEventRequest {
        WebRtcEventRequest {
            source,
            event_type,
            data: None,
            device,
            stream: None,
        }
    }
}


