# Generated by Django 3.1.7 on 2021-04-28 21:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import print_nanny_webapp.utils.fields


class Migration(migrations.Migration):


    dependencies = [
        ('remote_control', '0042_auto_20210207_2249_squashed_0049_auto_20210321_1313_squashed_0061_auto_20210425_2253'),
        ('remote_control', '0002_auto_20201126_1453_squashed_0040_octoprintdevice_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=255)),
                ('labels', models.FileField(upload_to='')),
                ('artifacts', models.FileField(upload_to='')),
                ('artifact_types', print_nanny_webapp.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('TFLITE', 'TensorFlow Lite Flatbuffer'), ('TF1', 'TensorFlow v1 SavedModel format (legacy)'), ('TF2_SAVED_MODEL', 'TensorFlow v2 SavedModel format'), ('TF2_HDF5', 'TensorFlow v2 Keras H5 format')], max_length=255), default=('TFLITE', 'TF2_SAVED_MODEL'), size=None)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('hypothesis', models.CharField(max_length=255)),
                ('notion_url', models.CharField(max_length=255, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='ml_ops.modelartifact')),
                ('treatments', models.ManyToManyField(blank=True, null=True, related_name='treatment', to='ml_ops.ModelArtifact')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentDeviceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('experiment_group', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_control.octoprintdevice')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_ops.experiment')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_ops.modelartifact')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCalibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('fpm', models.IntegerField(null=True)),
                ('coordinates', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('mask', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('octoprint_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='remote_control.octoprintdevice')),
                ('config_file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
