# Generated by Django 3.1.3 on 2021-02-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_ops', '0008_devicecalibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecalibration',
            name='fpm',
            field=models.IntegerField(null=True),
        ),
    ]
