# Generated by Django 3.1.3 on 2021-02-13 20:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_ops', '0009_devicecalibration_fpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecalibration',
            name='coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
