# Generated by Django 3.2.12 on 2022-02-24 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_auto_20220217_2202"),
        ("events", "0004_auto_20220221_0253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webrtcevent",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webrtc_events",
                to="devices.device",
            ),
        ),
        migrations.CreateModel(
            name="TestEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[("mqtt_ping", "Ping"), ("mqtt_pong", "Pong")],
                        max_length=32,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_events",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "index_together": {("device", "event_name")},
            },
            bases=("events.event",),
        ),
    ]
