# Generated by Django 3.2.12 on 2022-03-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0012_auto_20220305_2030"),
        ("events", "0007_rename_mqtt_webrtcevent_send_mqtt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webrtcevent",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="devices.janusstream"
            ),
        ),
    ]
