# Generated by Django 3.2.12 on 2022-04-12 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0014_auto_20220401_1652"),
        ("events", "0009_octoprintevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webrtcevent",
            name="send_mqtt",
        ),
        migrations.AlterField(
            model_name="webrtcevent",
            name="event_name",
            field=models.CharField(
                choices=[
                    (
                        "stream_start_success",
                        "Successfully created WebRTC Mountpoint, returns Janus streaming plugin info repsponse",
                    ),
                    ("stream_start_error", "Error creating WebRTC Mountpoint"),
                    (
                        "stream_stop_success",
                        "Successfully tore down WebRTC Mountpoint, returns Janus streaming plugin destroyed response",
                    ),
                    (
                        "stream_stop_error",
                        "Error tearing down WebRTC Mountpoint, returns Janus streaming plugin error response",
                    ),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="webrtcevent",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webrtc_events",
                to="devices.janusstream",
            ),
        ),
        migrations.CreateModel(
            name="WebRTCCommand",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            (
                                "stream_start",
                                "Initialize WebRTC mountpoint via Janus Gateway streaming plugin",
                            ),
                            (
                                "stream_stop",
                                "Initialize teardown of WebRTC mountpoint via Janus Gateway streaming plugin",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webrtc_commands",
                        to="devices.device",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webrtc_commands",
                        to="devices.janusstream",
                    ),
                ),
            ],
            options={
                "index_together": {("device", "stream", "event_name")},
            },
            bases=("events.event",),
        ),
    ]
