# Generated by Django 3.2.12 on 2022-06-20 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0024_alter_systeminfo_device"),
        ("octoprint", "0015_rename_octoprintinstall_octoprintserver"),
        ("events", "0011_auto_20220415_0329"),
    ]

    operations = [
        migrations.RenameField(
            model_name="octoprintevent",
            old_name="octoprint_install",
            new_name="octoprint_server",
        ),
        migrations.AlterIndexTogether(
            name="octoprintevent",
            index_together={("octoprint_server", "device", "event_name")},
        ),
    ]
