# Generated by Django 3.2.12 on 2022-08-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0029_alter_pibootcommand_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basepievent",
            name="payload",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="printjobalert",
            name="payload",
            field=models.JSONField(null=True),
        ),
    ]
