# Generated by Django 4.1.7 on 2023-03-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0036_remove_pibootcommand_basepievent_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjobalert",
            name="celery_task_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
