# Generated by Django 3.1.3 on 2020-12-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertvideomessage",
            name="job_status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="Processing",
                max_length=32,
            ),
        ),
    ]
