# Generated by Django 3.1.3 on 2020-11-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alertplot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectalert',
            name='dataframe',
        ),
        migrations.RemoveField(
            model_name='defectalert',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='defectalert',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='timelapsealert',
            name='dataframe',
        ),
        migrations.RemoveField(
            model_name='timelapsealert',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='timelapsealert',
            name='summary',
        ),
        migrations.AddField(
            model_name='alertmessage',
            name='feedback',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='alertplot',
            name='dataframe',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='alertplot',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertplot',
            name='function',
            field=models.CharField(default='foo', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertplot',
            name='html',
            field=models.FileField(default='foo', upload_to='uploads/alert_plot/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertplot',
            name='title',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
