# Generated by Django 3.2.2 on 2021-05-31 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_auto_20210505_1018"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertmessage",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="telemetry.telemetryevent",
            ),
        ),
    ]
