# Generated by Django 3.1.3 on 2020-12-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_auto_20201206_1719"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timelapsealert",
            name="notify_seconds",
        ),
        migrations.RemoveField(
            model_name="timelapsealert",
            name="notify_timecode",
        ),
        migrations.AddField(
            model_name="alertvideomessage",
            name="notify_seconds",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="alertvideomessage",
            name="notify_timecode",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
