# Generated by Django 3.2.2 on 2021-06-22 20:20

from django.db import migrations, models
import print_nanny_webapp.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_alertmessage_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertsettings",
            name="event_types",
            field=print_nanny_webapp.utils.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("PrintHealth", "Print health alerts"),
                        (
                            "PrintStatus",
                            "Print status updates (percent progress, paused, resumed, failed)",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=("PrintHealth", "PrintStatus"),
                size=None,
            ),
        ),
    ]
