# Generated by Django 3.1.3 on 2020-11-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20201124_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectalert',
            name='job_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='Processing', max_length=32),
        ),
        migrations.AddField(
            model_name='timelapsealert',
            name='job_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='Processing', max_length=32),
        ),
    ]
