# Generated by Django 3.1.3 on 2021-01-11 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alerts", "0004_auto_20201206_2018"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True, db_index=True)),
                ("dismissed", models.BooleanField(default=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_alerts.alert_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.RemoveField(
            model_name="alertvideomessage",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="alertvideomessage",
            name="user",
        ),
        migrations.RemoveField(
            model_name="defectalert",
            name="alertvideomessage_ptr",
        ),
        migrations.RemoveField(
            model_name="defectalert",
            name="print_job",
        ),
        migrations.AlterUniqueTogether(
            name="progressalert",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="progressalert",
            name="alertvideomessage_ptr",
        ),
        migrations.RemoveField(
            model_name="progressalert",
            name="print_job",
        ),
        migrations.RemoveField(
            model_name="timelapsealert",
            name="alertvideomessage_ptr",
        ),
        migrations.DeleteModel(
            name="AlertPlot",
        ),
        migrations.DeleteModel(
            name="AlertVideoMessage",
        ),
        migrations.DeleteModel(
            name="DefectAlert",
        ),
        migrations.DeleteModel(
            name="ProgressAlert",
        ),
        migrations.DeleteModel(
            name="TimelapseAlert",
        ),
    ]
