# Generated by Django 3.1.3 on 2020-11-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20201125_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectalert',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='timelapsealert',
            name='length',
            field=models.FloatField(null=True),
        ),
    ]
