# Generated by Django 3.1.3 on 2021-01-18 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import print_nanny_webapp.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0022_auto_20210117_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertsettings',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='defectalertsettings',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressalertsettings',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotecontrolcommandalertsettings',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alertsettings',
            name='alert_methods',
            field=print_nanny_webapp.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('UI', 'Recive Print Nanny UI notifations'), ('EMAIL', 'Receive email notifications')], max_length=255), blank=True, default=('UI',), size=None),
        ),
        migrations.AlterField(
            model_name='remotecontrolcommandalertsettings',
            name='move_nozzle',
            field=print_nanny_webapp.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('RECEIVED', 'Command was acknowledged by device'), ('FAILED', 'Command failed'), ('SUCCESS', 'Command succeeded')], max_length=255), blank=True, default=('FAILED',), help_text='Fires on <strong>MoveNozzle</strong>command status changes. Helpful for debugging connectivity between Print Nanny and OctoPrint', size=None),
        ),
        migrations.AlterField(
            model_name='remotecontrolcommandalertsettings',
            name='pause_print',
            field=print_nanny_webapp.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('RECEIVED', 'Command was acknowledged by device'), ('FAILED', 'Command failed'), ('SUCCESS', 'Command succeeded')], max_length=255), blank=True, default=('FAILED',), help_text='Fires on <strong>PausePrint</strong> command status changes. Helpful for verifying a print was paused successfully.', size=None),
        ),
        migrations.AlterField(
            model_name='remotecontrolcommandalertsettings',
            name='resume_print',
            field=print_nanny_webapp.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('RECEIVED', 'Command was acknowledged by device'), ('FAILED', 'Command failed'), ('SUCCESS', 'Command succeeded')], max_length=255), blank=True, default=('FAILED',), help_text='Fires on <strong>ResumePrint</strong> command status changes Helpful for verifying a print was resumed.', size=None),
        ),
        migrations.AlterField(
            model_name='remotecontrolcommandalertsettings',
            name='start_monitoring',
            field=print_nanny_webapp.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('RECEIVED', 'Command was acknowledged by device'), ('FAILED', 'Command failed'), ('SUCCESS', 'Command succeeded')], max_length=255), blank=True, default=('FAILED',), help_text='Fires on <strong>StopMonitoring</strong> updates. Helpful if you want to confirm monitoring started without a problem.', size=None),
        ),
        migrations.AlterField(
            model_name='remotecontrolcommandalertsettings',
            name='start_print',
            field=print_nanny_webapp.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('RECEIVED', 'Command was acknowledged by device'), ('FAILED', 'Command failed'), ('SUCCESS', 'Command succeeded')], max_length=255), blank=True, default=('FAILED',), help_text='Fires on <strong>SartPrint</strong> command status changes. Helpful for verifying a print job started without a problem.', size=None),
        ),
        migrations.AlterField(
            model_name='remotecontrolcommandalertsettings',
            name='stop_monitoring',
            field=print_nanny_webapp.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('RECEIVED', 'Command was acknowledged by device'), ('FAILED', 'Command failed'), ('SUCCESS', 'Command succeeded')], max_length=255), blank=True, default=('FAILED',), help_text='Fires on <strong>StopMonitoring<strong> updates. \n Helps debug unexpected Print Nanny crashes.', size=None),
        ),
        migrations.AlterField(
            model_name='remotecontrolcommandalertsettings',
            name='stop_print',
            field=print_nanny_webapp.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('RECEIVED', 'Command was acknowledged by device'), ('FAILED', 'Command failed'), ('SUCCESS', 'Command succeeded')], max_length=255), blank=True, default=('FAILED',), help_text='Fires on <strong>StopPrint</strong> updates. Get notifed as soon as a print job finishes. ', size=None),
        ),
        migrations.AlterUniqueTogether(
            name='alertsettings',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alertsettings',
            name='user',
        ),
    ]
