# Generated by Django 3.1.3 on 2021-01-18 05:51

from django.db import migrations, models
import print_nanny_webapp.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0025_auto_20210117_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotecontrolcommandalertsettings',
            name='snapshot',
            field=print_nanny_webapp.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('RECEIVED', 'Command was acknowledged by device'), ('FAILED', 'Command failed'), ('SUCCESS', 'Command succeeded')], max_length=255), blank=True, default=('FAILED', 'SUCCESS'), help_text='Fires on web camera <strong>Snapshot</strong> command', size=None),
        ),
    ]
