# Generated by Django 3.1.7 on 2021-04-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0028_auto_20210118_2015_squashed_0033_auto_20210228_2210"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='defectalert',
        #     name='print_job',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_control.printjob'),
        # ),
        migrations.AddField(
            model_name="alert",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
