# Generated by Django 3.1.7 on 2021-04-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0064_auto_20210427_2030"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printprogresseventsettings",
            name="alerteventsettings_ptr",
        ),
        migrations.DeleteModel(
            name="AlertEventSettings",
        ),
        migrations.DeleteModel(
            name="PrintProgressEventSettings",
        ),
    ]
