# Generated by Django 3.1.7 on 2021-04-28 21:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import print_nanny_webapp.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0040_auto_20210328_1610_squashed_0065_auto_20210427_2033"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertEventSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "event_types",
                    print_nanny_webapp.utils.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("PrintProgress", "Print progress notifications"),
                                ("PrintHealth", "Print health alerts"),
                                (
                                    "PrintStatus",
                                    "Print status updates (started, paused, resumed, cancelling, cancelled, failed)",
                                ),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        default=("PrintProgress", "PrintHealth", "PrintStatus"),
                        size=None,
                    ),
                ),
                (
                    "print_progress_percent",
                    models.IntegerField(
                        default=25,
                        help_text="Progress notification interval. Example: 25 will notify you at 25%, 50%, 75%, and 100% progress",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discord_webhook",
                    models.CharField(
                        blank=True,
                        help_text="Send notifications to a Discord channel. Please check out this guide to <a href='https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks'>generate a webhook</a> url and paste it here.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "alert_methods",
                    print_nanny_webapp.utils.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("UI", "Print Nanny UI"),
                                ("EMAIL", "Email notifications"),
                                ("DISCORD", "Discord channel (webhook)"),
                                ("PARTNER_3DGEEKS", "3D Geeks mobile app"),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        default=("EMAIL",),
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="alert",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PrintProgress", "Print progress notifications"),
                    ("PrintHealth", "Print health alerts"),
                    (
                        "PrintStatus",
                        "Print status updates (started, paused, resumed, cancelling, cancelled, failed)",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_method",
            field=models.CharField(
                choices=[
                    ("UI", "Receive Print Nanny UI notifications"),
                    ("EMAIL", "Receive email notifications"),
                    ("DISCORD", "Receive notifications through Discord"),
                    ("PARTNER_3DGEEKS", "Receive notifications in 3D Geeks mobile app"),
                ],
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="AlertMethodSettings",
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_method",
            field=models.CharField(
                choices=[
                    ("UI", "Print Nanny UI"),
                    ("EMAIL", "Email notifications"),
                    ("DISCORD", "Discord channel (webhook)"),
                    ("PARTNER_3DGEEKS", "3D Geeks mobile app"),
                ],
                max_length=255,
            ),
        ),
        migrations.RemoveField(
            model_name="remotecontrolcommandalert",
            name="alert_ptr",
        ),
        migrations.RemoveField(
            model_name="remotecontrolcommandalert",
            name="command",
        ),
        migrations.DeleteModel(
            name="ProgressAlert",
        ),
        migrations.DeleteModel(
            name="RemoteControlCommandAlert",
        ),
    ]
