# Generated by Django 3.1.7 on 2021-04-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0072_auto_20210427_2145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerteventsettings",
            name="discord_webhook",
            field=models.CharField(
                blank=True,
                help_text="Send notifications to a Discord channel. Please check out this guide to <a href='https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks'>generate a webhook</a> url and paste it here.",
                max_length=255,
                null=True,
            ),
        ),
    ]
