# Generated by Django 4.1.7 on 2023-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0003_workspace_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
