# Generated by Django 3.2.12 on 2022-11-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_emailwaitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
