# Generated by Django 4.1.7 on 2023-05-22 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_organization_slug"),
        ("users", "0008_alter_emailwaitlist_interest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("organizations.organization",),
        ),
        migrations.CreateModel(
            name="WorkspaceUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("organizations.organizationuser",),
        ),
    ]
