# Generated by Django 3.1.7 on 2021-04-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20210420_1648"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeeksToken",
        ),
    ]
