# Generated by Django 3.2.12 on 2023-01-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crash_reports", "0002_crashreport_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="crashreport",
            name="serial",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
