# Generated by Django 3.2.12 on 2022-10-28 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("email_campaigns", "0002_auto_20221028_2109"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="emailmessage",
            name="unique_esp_message_id_per_user",
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="email",
            field=models.EmailField(default="default@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailtrackingevent",
            name="recipient",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="emailtrackingevent",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterIndexTogether(
            name="emailmessage",
            index_together={("campaign", "user", "email", "message_id")},
        ),
    ]
