# coding: utf-8

"""
    printnanny-api-client

    Official API client library for print-nanny.com  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Contact: leigh@print-nanny.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import printnanny_api_client
from printnanny_api_client.models.octoprint_printer_data_request import OctoprintPrinterDataRequest  # noqa: E501
from printnanny_api_client.rest import ApiException

class TestOctoprintPrinterDataRequest(unittest.TestCase):
    """OctoprintPrinterDataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OctoprintPrinterDataRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = printnanny_api_client.models.octoprint_printer_data_request.OctoprintPrinterDataRequest()  # noqa: E501
        if include_optional :
            return OctoprintPrinterDataRequest(
                job = printnanny_api_client.models.octoprint_job_request.OctoprintJobRequest(
                    file = null, 
                    estimated_print_time = 1.337, 
                    average_print_time = 1.337, 
                    last_print_time = 1.337, 
                    filament = {
                        'key' : null
                        }, ), 
                state = printnanny_api_client.models.octoprint_printer_state_request.OctoprintPrinterStateRequest(
                    text = '0', 
                    flags = printnanny_api_client.models.octoprint_printer_flags_request.OctoprintPrinterFlagsRequest(
                        operational = True, 
                        printing = True, 
                        cancelling = True, 
                        pausing = True, 
                        resuming = True, 
                        finishing = True, 
                        closed_or_error = True, 
                        error = True, 
                        paused = True, 
                        ready = True, 
                        sd_ready = True, ), ), 
                user = '0', 
                current_z = 1.337, 
                progress = printnanny_api_client.models.octoprint_progress_request.OctoprintProgressRequest(
                    completion = 1.337, 
                    filepos = 56, 
                    print_time = 56, 
                    print_time_left = 56, 
                    print_time_origin = '0', ), 
                resends = {
                    'key' : null
                    }, 
                offsets = {
                    'key' : null
                    }
            )
        else :
            return OctoprintPrinterDataRequest(
                job = printnanny_api_client.models.octoprint_job_request.OctoprintJobRequest(
                    file = null, 
                    estimated_print_time = 1.337, 
                    average_print_time = 1.337, 
                    last_print_time = 1.337, 
                    filament = {
                        'key' : null
                        }, ),
                state = printnanny_api_client.models.octoprint_printer_state_request.OctoprintPrinterStateRequest(
                    text = '0', 
                    flags = printnanny_api_client.models.octoprint_printer_flags_request.OctoprintPrinterFlagsRequest(
                        operational = True, 
                        printing = True, 
                        cancelling = True, 
                        pausing = True, 
                        resuming = True, 
                        finishing = True, 
                        closed_or_error = True, 
                        error = True, 
                        paused = True, 
                        ready = True, 
                        sd_ready = True, ), ),
                progress = printnanny_api_client.models.octoprint_progress_request.OctoprintProgressRequest(
                    completion = 1.337, 
                    filepos = 56, 
                    print_time = 56, 
                    print_time_left = 56, 
                    print_time_origin = '0', ),
                resends = {
                    'key' : null
                    },
                offsets = {
                    'key' : null
                    },
        )

    def testOctoprintPrinterDataRequest(self):
        """Test OctoprintPrinterDataRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
