# Generated by Django 3.2.12 on 2022-08-01 03:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeeksToken",
        ),
    ]
