# Generated by Django 3.2.12 on 2023-01-21 23:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_rename_uuid_videorecording_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="videorecording",
            name="created_dt",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 1, 21, 23, 54, 49, 629423, tzinfo=utc),
            ),
            preserve_default=False,
        ),
    ]
