# Generated by Django 3.2.12 on 2023-03-01 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0006_auto_20230301_0923"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videorecording",
            name="capture_done",
        ),
    ]
