# Generated by Django 3.2.12 on 2023-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0009_auto_20230315_1547"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videorecording",
            name="combine_done",
        ),
        migrations.AddField(
            model_name="videorecording",
            name="finalize_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="videorecording",
            name="finalize_start",
            field=models.DateTimeField(null=True),
        ),
    ]
