# Generated by Django 4.1.7 on 2023-05-09 04:44

from django.db import migrations, models
import print_nanny_webapp.videos.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0015_camerasnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "submission",
                    models.FileField(
                        upload_to=print_nanny_webapp.videos.models.demo_submission_filepath
                    ),
                ),
                (
                    "result",
                    models.FileField(
                        upload_to=print_nanny_webapp.videos.models.demo_result_filepath
                    ),
                ),
            ],
            options={
                "ordering": ["-created_dt"],
                "index_together": {("id", "created_dt", "email")},
            },
        ),
    ]
