# Generated by Django 3.0.11 on 2020-11-12 07:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcode', models.FileField(upload_to='')),
                ('state', models.CharField(max_length=255)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_events.Printer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('event_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('plugin_version', models.CharField(max_length=30)),
                ('octoprint_version', models.CharField(max_length=30)),
                ('print_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_events.PrintJob')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_events.Printer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OctoPrintEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('event_type', models.CharField(max_length=30)),
                ('event_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('plugin_version', models.CharField(max_length=30)),
                ('octoprint_version', models.CharField(max_length=30)),
                ('print_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_events.PrintJob')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_events.Printer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
