# Generated by Django 3.1.3 on 2020-12-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictsession",
            name="channel_name",
            field=models.CharField(default="foo", max_length=255),
            preserve_default=False,
        ),
    ]
