# Generated by Django 3.1.3 on 2020-11-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicteventfile',
            name='annotated_image',
            field=models.ImageField(upload_to='uploads/predict_event/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='predicteventfile',
            name='original_image',
            field=models.ImageField(upload_to='uploads/predict_event/%Y/%m/%d/'),
        ),
    ]
