# Generated by Django 3.1.3 on 2020-12-27 22:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client_events", "0002_predictsession_channel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OctoPrintDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("private_key", models.FileField(upload_to="uploads/private_key/")),
                ("public_key", models.FileField(upload_to="uploads/public_key/")),
                ("model", models.CharField(max_length=255)),
                ("platform", models.CharField(max_length=255)),
                ("mac_address", models.CharField(max_length=255)),
                (
                    "cpu_flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
                ("hardware", models.CharField(max_length=255)),
                ("revision", models.CharField(max_length=255)),
                ("serial", models.CharField(max_length=255)),
                ("cores", models.IntegerField()),
                ("ram", models.IntegerField()),
                ("python_version", models.CharField(max_length=255)),
                ("pip_version", models.CharField(max_length=255)),
                ("virtualenv", models.CharField(max_length=255)),
                ("octoprint_version", models.CharField(max_length=255)),
                ("plugin_version", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "serial")},
            },
        ),
        migrations.RemoveField(
            model_name="predictsession",
            name="user",
        ),
        migrations.DeleteModel(
            name="PredictEvent",
        ),
        migrations.DeleteModel(
            name="PredictEventFile",
        ),
        migrations.DeleteModel(
            name="PredictSession",
        ),
    ]
