# Generated by Django 3.1.3 on 2020-11-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_events', '0002_predicteventfile_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='octoprintevent',
            name='print_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_events.printjob'),
        ),
    ]
