# Generated by Django 3.1.3 on 2020-11-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_events', '0002_auto_20201118_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmessage',
            name='last_action',
            field=models.CharField(choices=[('PENDING', 'Pending User Action'), ('ALERT_RESUMED', 'Alerts Resumed for Print Job'), ('PRINT_CANCELLED', 'Print Job Cancelled')], default='PENDING', max_length=16),
        ),
    ]
