# Generated by Django 3.1.3 on 2020-11-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_events', '0004_predictevent_predict_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='last_status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('CANCELLING', 'Cancelling'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed')], default='STARTED', max_length=12),
        ),
    ]
