# Generated by Django 3.1.3 on 2020-11-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_events', '0004_auto_20201113_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printerprofile',
            old_name='extruder_nozzleDiameter',
            new_name='extruder_nozzle_diameter',
        ),
        migrations.RenameField(
            model_name='printerprofile',
            old_name='extruder_sharedNozzle',
            new_name='extruder_shared_nozzle',
        ),
        migrations.RenameField(
            model_name='printerprofile',
            old_name='heatedBed',
            new_name='heated_bed',
        ),
        migrations.RenameField(
            model_name='printerprofile',
            old_name='heatedChamber',
            new_name='heated_chamber',
        ),
        migrations.RenameField(
            model_name='printerprofile',
            old_name='volume_customBox',
            new_name='volume_custom_box',
        ),
        migrations.RenameField(
            model_name='printerprofile',
            old_name='volume_formFactor',
            new_name='volume_formfactor',
        ),
    ]
