# Generated by Django 3.1.7 on 2021-03-08 00:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('remote_control', '0047_remove_printjob_last_status'),
        ('client_events', '0019_remove_printjobevent_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_client_events.clientevent_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PluginEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('bounding_box_predict', 'On-device bounding box prediction'), ('monitoring_frame_raw', 'Raw frame buffer sample'), ('monitoring_frame_post', 'Post-processed frame buffer'), ('device_register_start', 'Device registration started'), ('device_register_done', 'Device registration succeeded'), ('device_register_failed', 'Device registration failed'), ('printer_profile_sync_start', 'Printer profile sync started'), ('printer_profile_sync_done', 'Printer profile sync succeeded'), ('printer_profile_sync_failed', 'Printer profile sync failed')], db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJobState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Error', 'Error'), ('PrintCancelled', 'PrintCancelled'), ('PrintCancelling', 'PrintCancelling'), ('PrintDone', 'PrintDone'), ('PrintFailed', 'PrintFailed'), ('PrintPaused', 'PrintPaused'), ('PrintResumed', 'PrintResumed'), ('PrintStarted', 'PrintStarted')], db_index=True, max_length=255)),
                ('state', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('current_z', models.FloatField(null=True)),
                ('progress', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('job_data_file', models.CharField(max_length=255)),
                ('print_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_control.printjob')),
            ],
        ),
        migrations.RemoveField(
            model_name='printjobevent',
            name='device',
        ),
        migrations.RemoveField(
            model_name='printjobevent',
            name='print_job',
        ),
        migrations.RemoveField(
            model_name='printjobevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='octoprintevent',
            name='created_dt',
        ),
        migrations.RemoveField(
            model_name='octoprintevent',
            name='device',
        ),
        migrations.RemoveField(
            model_name='octoprintevent',
            name='event_data',
        ),
        migrations.RemoveField(
            model_name='octoprintevent',
            name='octoprint_version',
        ),
        migrations.RemoveField(
            model_name='octoprintevent',
            name='plugin_version',
        ),
        migrations.RemoveField(
            model_name='octoprintevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='ObjectDetectEventImage',
        ),
        migrations.DeleteModel(
            name='PrintJobEvent',
        ),
    ]
