# Generated by Django 3.1.3 on 2021-01-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_events", "0024_auto_20210120_2312"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printjobevent",
            name="temp_state2",
        ),
    ]
