const orderData = [
    {
        id: '#BM9708',
        date: 'August 05 2018',
        time: '10:29 PM',
        status: 'Paid',
        total: '$176.41',
        payment: 'Mastercard',
        orderStatus: 'Shipped',
    },
    {
        id: '#BM9707',
        date: 'August 04 2018',
        time: '08:18 AM',
        status: 'Awaiting Authorization',
        total: '$1,458.65',
        payment: 'Visa',
        orderStatus: 'Processing',
    },
    {
        id: '#BM9706',
        date: 'August 04 2018',
        time: '10:29 PM',
        status: 'Paid',
        total: '$801.99',
        payment: 'Credit Card',
        orderStatus: 'Processing',
    },
    {
        id: '#BM9705',
        date: 'August 03 2018',
        time: '07:56 AM',
        status: 'Paid',
        total: '$215.35',
        payment: 'Mastercard',
        orderStatus: 'Delivered',
    },
    {
        id: '#BM9704',
        date: 'May 22 2018',
        time: '07:22 PM',
        status: 'Payment Failed',
        total: '$2,514.36',
        payment: 'Paypal',
        orderStatus: 'Cancelled',
    },
    {
        id: '#BM9703',
        date: 'April 02 2018',
        time: '03:02 AM',
        status: 'Paid',
        total: '$183.20',
        payment: 'Payoneer',
        orderStatus: 'Shipped',
    },
    {
        id: '#BM9702',
        date: 'March 18 2018',
        time: '11:19 PM',
        status: 'Awaiting Authorization',
        total: '$1,768.41',
        payment: 'Visa',
        orderStatus: 'Processing',
    },
    {
        id: '#BM9701',
        date: 'February 01 2018',
        time: '07:22 AM',
        status: 'Unpaid',
        total: '$3,582.99',
        payment: 'Paypal',
        orderStatus: 'Shipped',
    },
    {
        id: '#BM9700',
        date: 'January 17 2018',
        time: '02:30 PM',
        status: 'Paid',
        total: '$5,177.68',
        payment: 'Mastercard',
        orderStatus: 'Shipped',
    },
];

export { orderData };