name: 'Lint'
description: 'Lint & typecheck Python webapp code'
runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Output repository secrets prefixed with TEST_ to run local setup
      shell: bash
      run: |
        echo "MAILGUN_API_KEY=${{ secrets.TEST_MAILGUN_API_KEY }}" > .envs/.local/.secrets
        echo "MAILGUN_DOMAIN=${{ secrets.TEST_MAILGUN_DOMAIN }}" >> .envs/.local/.secrets
        echo "HONEYCOMB_API_KEY=${{ secrets.TEST_HONEYCOMB_API_KEY }}" >> .envs/.local/.secrets
        echo "HONEYCOMB_API_KEY=${{ secrets.TEST_HONEYCOMB_API_KEY }}" >> .envs/.local/.secrets
        echo "DJSTRIPE_WEBHOOK_SECRET=${{ secrets.SANDBOX_DJSTRIPE_WEBHOOK_SECRET }}" >> .envs/.local/.secrets
        echo "STRIPE_TEST_PUBLIC_KEY=${{ secrets.SANDBOX_STRIPE_PUBLIC_KEY }}" >> .envs/.local/.secrets
        echo "STRIPE_TEST_SECRET_KEY=${{ secrets.SANDBOX_STRIPE_SECRET_KEY }}" >> .envs/.local/.secrets
        echo "POSTHOG_API_KEY=${{ secrets.TEST_POSTHOG_API_KEY }}" >> .envs/.local/.secrets