---
apiVersion: v1
kind: Service
metadata:
  namespace: nats
  name: nats-lb
  annotations:
    cloud.google.com/network-tier: "Standard"
spec:
  type: LoadBalancer
  loadBalancerIP: 35.208.7.161
  sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/name: nats
  ports:
    - name: client
      port: 4222
      protocol: TCP
      targetPort: 4222
    - name: websocket
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
    - name: leafnodes
      port: 7422
      protocol: TCP
      targetPort: 7422
