# Generated by Django 3.2.9 on 2022-01-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="setup_complete",
            field=models.BooleanField(default=False),
        ),
    ]
