# Generated by Django 3.2.7 on 2021-10-24 21:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnsibleFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("os_version", models.CharField(max_length=255)),
                ("os", models.CharField(max_length=255)),
                ("kernel_version", models.CharField(max_length=255)),
                ("hardware", models.CharField(max_length=255, null=True)),
                ("revision", models.CharField(max_length=255, null=True)),
                ("model", models.CharField(max_length=255, null=True)),
                ("serial", models.CharField(max_length=255, null=True)),
                ("cores", models.IntegerField()),
                ("ram", models.BigIntegerField()),
                (
                    "cpu_flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
                (
                    "release_channel",
                    models.CharField(
                        choices=[
                            ("main", "Stable mainline release channel"),
                            ("devel", "Unstable developer release channel"),
                        ],
                        default="main",
                        max_length=8,
                    ),
                ),
                ("json", models.JSONField()),
            ],
            options={
                "ordering": ["-created_dt"],
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "camera_type",
                    models.CharField(
                        choices=[
                            (
                                "Raspberry Pi Camera Module",
                                "Raspberry Pi Camera Module",
                            ),
                            ("Raspberry Pi USB Camera", "Raspberry Pi USB Camera"),
                            (
                                "Generic RTSP/RTMP IP Camera",
                                "Generic RTSP/RTMP IP Camera",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("camera_source", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CloudiotDevice",
            fields=[
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("num_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("id", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DevicePublicKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("public_key", models.TextField()),
                ("public_key_checksum", models.CharField(max_length=255)),
                ("fingerprint", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="cameracontroller",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="cameracontroller",
            name="device",
        ),
        migrations.RemoveField(
            model_name="cameracontroller",
            name="user",
        ),
        migrations.RemoveField(
            model_name="octoprintcontroller",
            name="printercontroller_ptr",
        ),
        migrations.RemoveField(
            model_name="octoprintprinterprofile",
            name="octoprint_controller",
        ),
        migrations.RemoveField(
            model_name="octoprintprinterprofile",
            name="printerprofile_ptr",
        ),
        migrations.AlterUniqueTogether(
            name="printerprofile",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="printerprofile",
            name="controller",
        ),
        migrations.RemoveField(
            model_name="printerprofile",
            name="device",
        ),
        migrations.RemoveField(
            model_name="printerprofile",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="printerprofile",
            name="user",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="cloudiot_device_name",
            new_name="hostname",
        ),
        migrations.RemoveField(
            model_name="printercontroller",
            name="cli_version",
        ),
        migrations.AddField(
            model_name="printercontroller",
            name="software",
            field=models.CharField(
                choices=[("OctoPrint", "OctoPrint printer controller")],
                default="OctoPrint",
                max_length=12,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("user", "hostname"),
                name="unique_device_hostname_per_user",
            ),
        ),
        migrations.DeleteModel(
            name="CameraController",
        ),
        migrations.DeleteModel(
            name="OctoprintController",
        ),
        migrations.DeleteModel(
            name="OctoprintPrinterProfile",
        ),
        migrations.DeleteModel(
            name="PrinterProfile",
        ),
        migrations.AddField(
            model_name="devicepublickey",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_keys",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="cloudiotdevice",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cloudiot_devices",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cameras",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="ansiblefacts",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ansible_facts",
                to="devices.device",
            ),
        ),
        migrations.RemoveField(
            model_name="device",
            name="cloudiot_device_num_id",
        ),
        migrations.RemoveField(
            model_name="device",
            name="cloudiot_device_path",
        ),
        migrations.RemoveField(
            model_name="device",
            name="cores",
        ),
        migrations.RemoveField(
            model_name="device",
            name="cpu_flags",
        ),
        migrations.RemoveField(
            model_name="device",
            name="fingerprint",
        ),
        migrations.RemoveField(
            model_name="device",
            name="hardware",
        ),
        migrations.RemoveField(
            model_name="device",
            name="kernel_version",
        ),
        migrations.RemoveField(
            model_name="device",
            name="model",
        ),
        migrations.RemoveField(
            model_name="device",
            name="name",
        ),
        migrations.RemoveField(
            model_name="device",
            name="os",
        ),
        migrations.RemoveField(
            model_name="device",
            name="os_version",
        ),
        migrations.RemoveField(
            model_name="device",
            name="public_key",
        ),
        migrations.RemoveField(
            model_name="device",
            name="ram",
        ),
        migrations.RemoveField(
            model_name="device",
            name="revision",
        ),
        migrations.RemoveField(
            model_name="device",
            name="serial",
        ),
        migrations.AddConstraint(
            model_name="devicepublickey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("device",),
                name="unique_public_key_per_device",
            ),
        ),
        migrations.AddConstraint(
            model_name="cloudiotdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("device",),
                name="unique_cloud_iot_device_per_device",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="camera",
            unique_together={("user", "name")},
        ),
    ]
