# Generated by Django 3.2.7 on 2021-10-25 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_auto_20211024_2145"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("ansible_facts", models.JSONField(default={})),
                ("ansible_extra_vars", models.JSONField(default={})),
                (
                    "release_channel",
                    models.CharField(
                        choices=[
                            ("stable", "Stable mainline release channel"),
                            ("nightly", "Nightly developer release channel"),
                        ],
                        default="stable",
                        max_length=8,
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_dt"],
            },
        ),
        migrations.CreateModel(
            name="DeviceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("ansible_extra_vars", models.JSONField(default={})),
                (
                    "release_channel",
                    models.CharField(
                        choices=[
                            ("stable", "Stable mainline release channel"),
                            ("nightly", "Nightly developer release channel"),
                        ],
                        default="stable",
                        max_length=8,
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_dt"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="cores",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="hardware",
            field=models.CharField(default="hardware", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="model",
            field=models.CharField(default="model", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="ram",
            field=models.BigIntegerField(default=12345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="revision",
            field=models.CharField(default="revision", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="serial",
            field=models.CharField(default="serial", max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AnsibleFacts",
        ),
        migrations.AddField(
            model_name="desiredconfig",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="devices.device"
            ),
        ),
        migrations.AddField(
            model_name="currentstate",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="devices.device"
            ),
        ),
    ]
