# Generated by Django 3.2.7 on 2021-10-10 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("devices", "0003_alter_ansiblefacts_release_channel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "camera_type",
                    models.CharField(
                        choices=[
                            (
                                "Raspberry Pi Camera Module",
                                "Raspberry Pi Camera Module",
                            ),
                            ("Raspberry Pi USB Camera", "Raspberry Pi USB Camera"),
                            (
                                "Generic RTSP/RTMP IP Camera",
                                "Generic RTSP/RTMP IP Camera",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("camera_source", models.CharField(max_length=255)),
                (
                    "camera_source_type",
                    models.CharField(
                        choices=[
                            ("MJPG Streamer", "Software-encoded JPG frames over HTTP"),
                            ("Gstreamer", "Hardware-encoded h264"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "appliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="devices.appliance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="PrinterController",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "software",
                    models.CharField(
                        choices=[("OctoPrint", "OctoPrint printer controller")],
                        max_length=12,
                    ),
                ),
                (
                    "appliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="printer_controllers",
                        to="devices.appliance",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_devices.printercontroller_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="printer_controllers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="device",
            name="user",
        ),
        migrations.RemoveField(
            model_name="AppliancePublicKey",
            name="private_key_checksum",
        ),
        migrations.DeleteModel(
            name="CameraController",
        ),
        migrations.DeleteModel(
            name="Device",
        ),
    ]
