# Generated by Django 3.2.12 on 2022-02-17 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import print_nanny_webapp.devices.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("devices", "0005_auto_20220217_0412"),
    ]

    operations = [
        migrations.CreateModel(
            name="JanusAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("admin_secret", models.CharField(max_length=255, null=True)),
                (
                    "api_token",
                    models.CharField(
                        default=print_nanny_webapp.devices.models.get_random_string_32,
                        max_length=255,
                    ),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("cloud", "Cloud WebRTC Gateway"),
                            ("edge", "Edge WebRTC Gateway"),
                        ],
                        default="cloud",
                        max_length=32,
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="janus_cloud_auth",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterIndexTogether(
            name="janusedgeauth",
            index_together=None,
        ),
        migrations.RemoveField(
            model_name="janusedgeauth",
            name="device",
        ),
        migrations.AlterField(
            model_name="janusstreamconfig",
            name="config_type",
            field=models.CharField(
                choices=[
                    ("cloud", "Cloud WebRTC Gateway"),
                    ("edge", "Edge WebRTC Gateway"),
                ],
                default="cloud",
                max_length=32,
            ),
        ),
        migrations.DeleteModel(
            name="JanusCloudAuth",
        ),
        migrations.DeleteModel(
            name="JanusEdgeAuth",
        ),
    ]
