# Generated by Django 3.2.12 on 2022-02-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0009_auto_20220225_2135"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="janusstream",
            name="unique_port",
        ),
        migrations.AddConstraint(
            model_name="janusstream",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("rtp_port",),
                name="unique_port",
            ),
        ),
    ]
