# Generated by Django 3.2.7 on 2021-11-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0010_alter_devicestate_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceinfo",
            name="image_version",
            field=models.CharField(
                default="default",
                help_text="Print Nanny OS version string from /boot/image_version.txt",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
