# Generated by Django 3.2.9 on 2021-12-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0016_rename_url_systemtask_wiki_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for Pi to acknowledge task"),
                    ("started", "Running"),
                    ("failed", "Failed"),
                    ("success", "Success"),
                ],
                default="waiting",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="systemtask",
            name="type",
            field=models.CharField(
                choices=[
                    ("activate_license", "Activate License"),
                    ("software_update", "Software Update"),
                ],
                default="software_update",
                max_length=255,
            ),
        ),
    ]
