# Generated by Django 3.2.12 on 2022-07-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0028_auto_20220711_2203"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicesettings",
            name="octoprint_enabled",
        ),
    ]
