# Generated by Django 3.2.9 on 2021-12-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0031_camera_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("failed", "Task failed."),
                    ("pending", "Waiting for device to acknowledge task."),
                    ("started", "Task is running."),
                    ("success", "Task succeeded."),
                    ("timeout", "Task timed out. Please try again."),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
