# Generated by Django 3.2.12 on 2022-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0039_delete_cloudiotdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinatsapp",
            name="allow_pub",
            field=models.CharField(
                help_text="add publish permissions, comma separated list. equivalent to `nsc add user ... --allow-pub=<permissions>`",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pinatsapp",
            name="allow_pubsub",
            field=models.CharField(
                help_text="add publish/subscribe permissions, comma separated list. equivalent to `nsc add user ... --allow-pubsub=<permissions>`",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pinatsapp",
            name="allow_sub",
            field=models.CharField(
                help_text="add subscribe permissions, comma separated list. equivalent to `nsc add user ... --allow-sub=<permissions>`",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pinatsapp",
            name="deny_pub",
            field=models.CharField(
                help_text="deny publish permissions, comma separated list. equivalent to `nsc add user ... --deny-pub=<permissions>`",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pinatsapp",
            name="deny_pubsub",
            field=models.CharField(
                help_text="deny publish/subscribe permissions, comma separated list. equivalent to `nsc add user ... --deny-pubsub=<permissions>`",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pinatsapp",
            name="deny_sub",
            field=models.CharField(
                help_text="deny subscribe permissions, comma separated list. equivalent to `nsc add user ... --deny-sub=<permissions>`",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pinatsapp",
            name="json",
            field=models.JSONField(
                default=dict,
                help_text="Output of `nsc describe account`",
                max_length=255,
            ),
        ),
    ]
