# Generated by Django 3.2.12 on 2022-08-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0042_webrtcstream_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pi",
            name="favorite",
            field=models.BooleanField(default=True),
        ),
    ]
