# Generated by Django 3.2.9 on 2022-01-28 22:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0045_alter_publickey_cipher"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cloudiotdevice",
            name="unique_cloud_iot_device_per_device",
        ),
        migrations.AddField(
            model_name="cloudiotdevice",
            name="created_dt",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cloudiotdevice",
            name="public_key",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cloudiot_devices",
                to="devices.publickey",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cloudiotdevice",
            name="updated_dt",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddConstraint(
            model_name="cloudiotdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("device", "public_key"),
                name="unique_cloud_iot_device_per_device",
            ),
        ),
    ]
