name: 'Lint'
description: 'Lint & typecheck Python webapp code'
runs:
  using: "composite"
  steps:
    # Runs a set of commands using the runners shell
    - name: Linter
      shell: bash
      run: |
        make lint
    - name: Mypy
      shell: bash
      run: |
        make mypy