# Generated by Django 3.2.2 on 2021-05-29 20:47

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("remote_control", "0005_alter_remotecontrolcommand_command"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telemetry", "0007_alter_octoprintevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintNannyPluginEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("event_data", models.JSONField(null=True)),
                ("plugin_version", models.CharField(max_length=60)),
                ("client_version", models.CharField(max_length=60)),
                ("octoprint_version", models.CharField(max_length=60)),
                ("metadata", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                (
                    "octoprint_job",
                    django.contrib.postgres.fields.jsonb.JSONField(null=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            (
                                "plugin_octoprint_nanny_monitoring_start",
                                "Print Nanny Monitoring started",
                            ),
                            (
                                "plugin_octoprint_nanny_monitoring_stop",
                                "Print Nanny Monitoring stopped",
                            ),
                            (
                                "plugin_octoprint_nanny_monitoring_reset",
                                "Print Nanny Monitoring reset",
                            ),
                            (
                                "plugin_octoprint_nanny_device_register_start",
                                "Device registration started",
                            ),
                            (
                                "plugin_octoprint_nanny_device_register_done",
                                "Device registration succeeded",
                            ),
                            (
                                "plugin_octoprint_nanny_device_register_failed",
                                "Device registration failed",
                            ),
                            ("device_reset", "Device identity reset"),
                            (
                                "plugin_octoprint_nanny_printer_profile_sync_start",
                                "Printer profile sync started",
                            ),
                            (
                                "plugin_octoprint_nanny_printer_profile_sync_done",
                                "Printer profile sync succeeded",
                            ),
                            (
                                "plugin_octoprint_nanny_printer_profile_sync_failed",
                                "Printer profile sync failed",
                            ),
                            ("connect_test_rest_api", "Test connection to REST API"),
                            (
                                "plugin_octoprint_nanny_connect_test_rest_api_failed",
                                "Test connection to REST API failed",
                            ),
                            (
                                "plugin_octoprint_nanny_connect_test_rest_api_success",
                                "Test connection to REST API success",
                            ),
                            (
                                "plugin_octoprint_nanny_connect_test_mqtt_ping",
                                "Test connection to REST API",
                            ),
                            (
                                "plugin_octoprint_nanny_connect_test_mqtt_ping_failed",
                                "Test connection to REST API failed",
                            ),
                            (
                                "plugin_octoprint_nanny_connect_test_mqtt_ping_success",
                                "Test connection to REST API success",
                            ),
                            (
                                "plugin_octoprint_nanny_connect_test_mqtt_pong",
                                "Test connection to REST API",
                            ),
                            (
                                "plugin_octoprint_nanny_connect_test_mqtt_pong_failed",
                                "Test connection to REST API failed",
                            ),
                            (
                                "plugin_octoprint_nanny_connect_test_mqtt_pong_success",
                                "Test connection to REST API success",
                            ),
                        ],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                (
                    "octoprint_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="remote_control.octoprintdevice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="remotecommandevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("remote_command_received", "Command was received by device"),
                    (
                        "remote_command_failed",
                        "Command failed. Please download your Octoprint logs and open a Github issue to get this fixed.",
                    ),
                    ("remote_command_success", "Command succeeded"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="OctoPrintPluginEvent",
        ),
    ]
