# Generated by Django 3.2.2 on 2021-05-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0009_octoprintevent_printnannypluginevent_printstatusevent_remotecommandevent_telemetryevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetryevent',
            name='octoprint_metadata',
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='octoprint_environment',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='octoprint_printer_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='temperature',
            field=models.JSONField(default=dict),
        ),
    ]
