# Generated by Django 3.2.2 on 2021-05-31 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0010_auto_20210530_1607"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telemetryevent",
            name="octoprint_job",
        ),
    ]
