# Generated by Django 3.2.2 on 2021-05-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0012_remove_telemetryevent_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printstatusevent',
            name='current_z',
        ),
        migrations.RemoveField(
            model_name='printstatusevent',
            name='job_data_file',
        ),
        migrations.RemoveField(
            model_name='printstatusevent',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='printstatusevent',
            name='state',
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='octoprint_version',
            field=models.CharField(default='Not detected', max_length=36),
            preserve_default=False,
        ),
    ]
