# Generated by Django 3.2.2 on 2021-05-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0014_auto_20210530_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetryevent',
            name='octoprint_device',
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='octoprint_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='telemetryevent',
            name='event_data',
            field=models.JSONField(default=dict),
        ),
    ]
