# Generated by Django 3.2.12 on 2022-11-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="type",
            field=models.CharField(
                choices=[
                    ("FreeBeta", "Participated in free beta program"),
                    (
                        "FoundingMember",
                        "Supported PrintNanny by pre-ordering an annual subscription",
                    ),
                ],
                max_length=24,
            ),
        ),
    ]
