/**
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.print-nanny.client.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * Abstract class inspired by DRF's own token serializer. Returns a user if valid, None or a message if not.
 *
 * @param token 
 * @param email 
 * @param mobile 
 */

data class CallbackTokenAuthRequest (

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "mobile")
    val mobile: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

