/**
* 
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.print-nanny.client.models


import com.squareup.moshi.Json

/**
* 
* Values: monitoringActive,renderingVideo,doneATimelapseOfYourPrintJobIsReadyExclamation
*/

enum class MonitoringStatusEnum(val value: kotlin.String) {


    @Json(name = "monitoring_active")
    monitoringActive("monitoring_active"),

    @Json(name = "rendering_video")
    renderingVideo("rendering_video"),

    @Json(name = "doneA timelapse of your print job is ready!")
    doneATimelapseOfYourPrintJobIsReadyExclamation("doneA timelapse of your print job is ready!");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }
}

