/**
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.print-nanny.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: monitoringStart,monitoringStop,monitoringReset,deviceRegisterStart,deviceRegisterDone,deviceRegisterFailed,deviceReset,printerProfileSyncStart,printerProfileSyncDone,printerProfileSyncFailed,connectTestRestApi,connectTestRestApiFailed,connectTestRestApiSuccess,connectTestMqttPing,connectTestMqttPingFailed,connectTestMqttPingSuccess,connectTestMqttPong,connectTestMqttPongFailed,connectTestMqttPongSuccess
 */

enum class PrintNannyPluginEventEventTypeEnum(val value: kotlin.String) {

    @Json(name = "plugin_octoprint_nanny_monitoring_start")
    monitoringStart("plugin_octoprint_nanny_monitoring_start"),

    @Json(name = "plugin_octoprint_nanny_monitoring_stop")
    monitoringStop("plugin_octoprint_nanny_monitoring_stop"),

    @Json(name = "plugin_octoprint_nanny_monitoring_reset")
    monitoringReset("plugin_octoprint_nanny_monitoring_reset"),

    @Json(name = "plugin_octoprint_nanny_device_register_start")
    deviceRegisterStart("plugin_octoprint_nanny_device_register_start"),

    @Json(name = "plugin_octoprint_nanny_device_register_done")
    deviceRegisterDone("plugin_octoprint_nanny_device_register_done"),

    @Json(name = "plugin_octoprint_nanny_device_register_failed")
    deviceRegisterFailed("plugin_octoprint_nanny_device_register_failed"),

    @Json(name = "plugin_octoprint_nanny_device_reset")
    deviceReset("plugin_octoprint_nanny_device_reset"),

    @Json(name = "plugin_octoprint_nanny_printer_profile_sync_start")
    printerProfileSyncStart("plugin_octoprint_nanny_printer_profile_sync_start"),

    @Json(name = "plugin_octoprint_nanny_printer_profile_sync_done")
    printerProfileSyncDone("plugin_octoprint_nanny_printer_profile_sync_done"),

    @Json(name = "plugin_octoprint_nanny_printer_profile_sync_failed")
    printerProfileSyncFailed("plugin_octoprint_nanny_printer_profile_sync_failed"),

    @Json(name = "plugin_octoprint_nanny_connect_test_rest_api")
    connectTestRestApi("plugin_octoprint_nanny_connect_test_rest_api"),

    @Json(name = "plugin_octoprint_nanny_connect_test_rest_api_failed")
    connectTestRestApiFailed("plugin_octoprint_nanny_connect_test_rest_api_failed"),

    @Json(name = "plugin_octoprint_nanny_connect_test_rest_api_success")
    connectTestRestApiSuccess("plugin_octoprint_nanny_connect_test_rest_api_success"),

    @Json(name = "plugin_octoprint_nanny_connect_test_mqtt_ping")
    connectTestMqttPing("plugin_octoprint_nanny_connect_test_mqtt_ping"),

    @Json(name = "plugin_octoprint_nanny_connect_test_mqtt_ping_failed")
    connectTestMqttPingFailed("plugin_octoprint_nanny_connect_test_mqtt_ping_failed"),

    @Json(name = "plugin_octoprint_nanny_connect_test_mqtt_ping_success")
    connectTestMqttPingSuccess("plugin_octoprint_nanny_connect_test_mqtt_ping_success"),

    @Json(name = "plugin_octoprint_nanny_connect_test_mqtt_pong")
    connectTestMqttPong("plugin_octoprint_nanny_connect_test_mqtt_pong"),

    @Json(name = "plugin_octoprint_nanny_connect_test_mqtt_pong_failed")
    connectTestMqttPongFailed("plugin_octoprint_nanny_connect_test_mqtt_pong_failed"),

    @Json(name = "plugin_octoprint_nanny_connect_test_mqtt_pong_success")
    connectTestMqttPongSuccess("plugin_octoprint_nanny_connect_test_mqtt_pong_success");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): kotlin.String? = if (data is PrintNannyPluginEventEventTypeEnum) "$data" else null

        /**
         * Returns a valid [PrintNannyPluginEventEventTypeEnum] for [data], null otherwise.
         */
        fun decode(data: Any?): PrintNannyPluginEventEventTypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

