const customersData = [
    {
        image: require('@assets/images/users/avatar-2.jpg'),
        name: 'Rory Seekamp',
        phone: '078 5054 8877',
        email: 'roryamp@dayrep.com',
        location: 'United States',
        date: '03/24/2018',
        status: 'Blocked',
    },
    {
        image: require('@assets/images/users/avatar-10.jpg'),
        name: 'Dean Smithies',
        phone: '077 6157 4248',
        email: 'deanes@dayrep.com',
        location: 'Singapore',
        date: '04/09/2018',
        status: 'Active',
    },
    {
        image: require('@assets/images/users/avatar-9.jpg'),
        name: 'Anna Ciantar',
        phone: '(216) 76 298 896',
        email: 'annac@hotmai.us',
        location: 'Philippines',
        date: '05/06/2018',
        status: 'Active',
    },
    {
        image: require('@assets/images/users/avatar-1.jpg'),
        name: 'Labeeb Ghali',
        phone: '050 414 8778',
        email: 'labebswad@teleworm.us',
        location: 'United Kingdom',
        date: '06/19/2018',
        status: 'Active',
    },
    {
        image: require('@assets/images/users/avatar-3.jpg'),
        name: 'Kathryn S. Collier',
        phone: '828-216-2190',
        email: 'collier@jourrapide.com',
        location: 'Canada',
        date: '06/30/2018',
        status: 'Blocked',
    },
    {
        image: require('@assets/images/users/avatar-4.jpg'),
        name: 'Paul J. Friend',
        phone: '937-330-1634',
        email: 'pauljfrnd@jourrapide.com',
        location: 'New York',
        date: '07/07/2018',
        status: 'Active',
    },
    {
        image: require('@assets/images/users/avatar-5.jpg'),
        name: 'Zara Raws',
        phone: '(02) 75 150 655',
        email: 'austin@dayrep.com',
        location: 'Germany',
        date: '07/15/2018',
        status: 'Active',
    },
    {
        image: require('@assets/images/users/avatar-7.jpg'),
        name: 'Jenny C. Gero',
        phone: '078 7173 9261',
        email: 'jennygero@teleworm.us',
        location: 'Lesotho',
        date: '08/02/2018',
        status: 'Blocked',
    },
    {
        image: require('@assets/images/users/avatar-8.jpg'),
        name: 'Edward Roseby',
        phone: '078 6013 3854',
        email: 'edwardR@armyspy.com',
        location: 'Monaco',
        date: '08/23/2018',
        status: 'Active',
    },
    {
        image: require('@assets/images/users/avatar-6.jpg'),
        name: 'Annette P. Kelsch',
        phone: '(+15) 73 483 758',
        email: 'annette@email.net',
        location: 'India',
        date: '09/05/2018',
        status: 'Active',
    },
    {
        image: require('@assets/images/users/avatar-1.jpg'),
        name: 'Timothy Kauper',
        phone: '(216) 75 612 706',
        email: 'thykauper@rhyta.com',
        location: 'Denmark',
        date: '09/08/2018',
        status: 'Blocked',
    },
    {
        image: require('@assets/images/users/avatar-3.jpg'),
        name: 'Bryan J. Luellen',
        phone: '215-302-3376',
        email: 'bryuellen@dayrep.com',
        location: 'New York',
        date: '09/12/2018',
        status: 'Active',
    },
];

export { customersData };
