{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windmill
  template:
    metadata:
      labels: 
        app: windmill
        container: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
        - name: "POSTGRES_PASSWORD"
          value: "{{ .Values.postgres.password }}"
        - name: "POSTGRES_DB"
          value: "{{ .Values.postgres.dbName }}"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: windmill
    container: postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- else }}

{{- end }}
