#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput

NATS_SERVER_URI="${NATS_SERVER_URI:-nats://nats:4222}"
NKEYS_IMPORT_DIR="${NKEYS_IMPORT_DIR:-/etc/django-operator-nkeys}"
DJANGO_OPERATOR_JWT="${DJANGO_OPERATOR_JWT:-/etc/django-operator-nkeys/operator.jwt}"
SYSTEM_ACCOUNT_JWT="${SYSTEM_ACCOUNT_JWT:-/etc/django-operator-nkeys/SYS.jwt}"
SYSTEM_USER_JWT="${SYSTEM_USER_JWT:-/etc/django-operator-nkeys/sys.jwt}"


compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

python manage.py migrate

# import operator.jwt if /etc/django-operator-nkeys/ mount available
if [ -f "$DJANGO_OPERATOR_JWT" ] && [ -f "$SYSTEM_ACCOUNT_JWT" ] && [ -f "$SYSTEM_USER_JWT"  ]
then
    echo "Importing nkeys from $NKEYS_IMPORT_DIR"
    nsc import keys --dir "$NKEYS_IMPORT_DIR" --keystore-dir=/var/lib/nats/nsc/keys --config-dir=/var/lib/nats/nsc/config --data-dir=/var/lib/nats/nsc/stores
    echo "Loading Operator JWT from $DJANGO_OPERATOR_JWT"
    python manage.py nsc_operator_jwt --import "$DJANGO_OPERATOR_JWT"
    echo "Setting operator --account-jwt-server-url $NATS_SERVER_URI"
    nsc edit operator --account-jwt-server-url "$NATS_SERVER_URI" --keystore-dir=/var/lib/nats/nsc/keys --config-dir=/var/lib/nats/nsc/config --data-dir=/var/lib/nats/nsc/stores
    echo "Loading account JWT from $SYSTEM_ACCOUNT_JWT"
    python manage.py nsc_account_jwt --import "$SYSTEM_ACCOUNT_JWT"
    echo "Loading user JWT from $SYSTEM_USER_JWT"
    python manage.py nsc_user_jwt --import "$SYSTEM_USER_JWT"
fi

python manage.py nsc_pull

# if compress_enabled; then
#   # NOTE this command will fail if django-compressor is disabled
#   python /app/manage.py compress
# fi
set +u
if [ "$DJANGO_SUPERUSER_EMAIL" ]
then
    python manage.py createsuperuser \
        --noinput \
        --email "$DJANGO_SUPERUSER_EMAIL" || \
    echo "User already exists: $DJANGO_SUPERUSER_EMAIL"
fi
set -u

uvicorn config.asgi:application --host 0.0.0.0