# Generated by Django 3.2.9 on 2022-01-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octoprint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="octoprintbackup",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
