# Generated by Django 3.2.12 on 2022-04-13 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("octoprint", "0011_auto_20220413_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="gcodefile",
            name="created_dt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
