# Generated by Django 3.2.12 on 2022-06-20 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0024_alter_systeminfo_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("octoprint", "0015_rename_octoprintinstall_octoprintserver"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="octoprintserver",
            name="unique_octoprint_install_per_device",
        ),
        migrations.RenameField(
            model_name="octoprintsettings",
            old_name="octoprint_install",
            new_name="octoprint_server",
        ),
        migrations.AlterField(
            model_name="octoprintserver",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="octoprint_servers",
                to="devices.device",
            ),
        ),
        migrations.AlterField(
            model_name="octoprintserver",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="octoprint_servers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="octoprintserver",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("device",),
                name="unique_octoprint_server_per_device",
            ),
        ),
    ]
