# Generated by Django 3.2.12 on 2022-08-11 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("devices", "0038_auto_20220807_2138"),
        ("octoprint", "0020_alter_octoprinterprofile_volume_custom_box"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseOctoPrintEvent",
            fields=[
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "octoprint_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="octoprint.octoprintserver",
                    ),
                ),
                (
                    "pi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.pi"
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_octoprint.baseoctoprintevent_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_dt"],
                "abstract": False,
                "index_together": {("id", "pi", "octoprint_server", "created_dt")},
            },
        ),
    ]
