---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: "sandbox-print-nanny-com-tls"
spec:
  domains:
    - "sandbox.print-nanny.com"
    - "octoprint.sandbox.print-nanny.com"
