---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "octoprint-pv-claim"
  labels:
    app: octoprint
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "postgres-pv-claim"
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi