# Generated by Django 3.1.3 on 2020-11-26 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("remote_control", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printjob",
            name="gcode_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="remote_control.gcodefile",
            ),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="printer_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="remote_control.printerprofile",
            ),
        ),
    ]
