# Generated by Django 3.1.3 on 2020-12-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("remote_control", "0003_printjob_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printjob",
            name="gcode_file_hash",
        ),
    ]
