# Generated by Django 3.1.3 on 2021-01-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_control", "0015_remotecontrolcommand_success"),
    ]

    operations = [
        migrations.AddField(
            model_name="octoprintdevice",
            name="monitoring_active",
            field=models.BooleanField(default=False),
        ),
    ]
