# Generated by Django 3.2.2 on 2021-06-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("remote_control", "0019_auto_20210622_2020"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="octoprintdevice",
            name="last_session",
        ),
    ]
