# Generated by Django 3.2.12 on 2022-08-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0008_auto_20220801_1541"),
        ("remote_control", "0026_octoprintdevice_print_nanny_beta_client_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="octoprintdevice",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="printerprofile",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="printerprofile",
            name="octoprint_device",
        ),
        migrations.RemoveField(
            model_name="printerprofile",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="printsession",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="printsession",
            name="gcode_file",
        ),
        migrations.RemoveField(
            model_name="printsession",
            name="octoprint_device",
        ),
        migrations.RemoveField(
            model_name="printsession",
            name="printer_profile",
        ),
        migrations.RemoveField(
            model_name="printsession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="remotecontrolcommand",
            name="device",
        ),
        migrations.RemoveField(
            model_name="remotecontrolcommand",
            name="user",
        ),
        migrations.DeleteModel(
            name="GcodeFile",
        ),
        migrations.DeleteModel(
            name="OctoPrintDevice",
        ),
        migrations.DeleteModel(
            name="PrinterProfile",
        ),
        migrations.DeleteModel(
            name="PrintSession",
        ),
        migrations.DeleteModel(
            name="RemoteControlCommand",
        ),
    ]
