# Generated by Django 3.1.3 on 2021-01-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_control", "0030_printjob_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printjob",
            name="last_status",
            field=models.CharField(
                choices=[
                    ("Error", "Error"),
                    ("PrintCancelled", "PrintCancelled"),
                    ("PrintCancelling", "PrintCancelling"),
                    ("PrintDone", "PrintDone"),
                    ("PrintFailed", "PrintFailed"),
                    ("PrintPaused", "PrintPaused"),
                    ("PrintResumed", "PrintResumed"),
                    ("PrintStarted", "PrintStarted"),
                ],
                default="PrintStarted",
                max_length=56,
            ),
        ),
    ]
