# Generated by Django 3.1.3 on 2021-02-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("remote_control", "0043_auto_20210207_2332"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="octoprintdevice",
            name="configs",
        ),
    ]
