# Generated by Django 3.1.7 on 2021-04-26 05:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_control", "0059_auto_20210421_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="octoprintdevice",
            name="cpu_flags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="octoprintdevice",
            name="hardware",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="octoprintdevice",
            name="revision",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
