#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

/usr/bin/ara-manage migrate

if [ "$DJANGO_SUPERUSER_EMAIL" && "$DJANGO_SUPERUSER_PASSWORD" ]
then
    python manage.py createsuperuser \
        --noinput \
        --email $DJANGO_SUPERUSER_EMAIL || \
    echo "User already exists: $DJANGO_SUPERUSER_EMAIL"
fi

/usr/bin/gunicorn-3 --workers=4 --access-logfile - --bind 0.0.0.0:8000 ara.server.wsgi