name: Bump & release api client versions
on:
  push:
    branches:
      - main
      - devel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install Python deps
      run: |
        pip install -r requirements/test.txt
    - name: Set output
      id: git
      run: echo ::set-output name=git_branch::${GITHUB_REF#refs/*/}
    - name: Bump version (dry run)
      id: tags
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
        RELEASE_BRANCHES: "main"
        PRERELEASE_SUFFIX: "dev"
    - name: Lint
      uses: ./.github/workflows/scripts/test-secrets
    - name: Commit version bump message
      run: |
        make local-up-d
        ./tools/bump-version-and-release-clients.sh ${{ steps.tags.outputs.tag }} ${{ steps.tags.outputs.new_tag }} ${{ steps.git.outputs.git_branch }}
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: false
        RELEASE_BRANCHES: "main"
        PRERELEASE_SUFFIX: "dev"
