name: Cypress

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start Django Webapp
        run: |
          make local-up-d
      - uses: cypress-io/github-action@v4.2.0
        with:
          build: npm run build
          start: npm run dev
