name: Cypress

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    environment: test
    env:
      DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
      DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
      NKEYS_PATH: /var/lib/nats/nsc/keys
      NSC_HOME: /var/lib/nats/nsc
      NSC_STORE: /var/lib/nats/nsc/stores
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Start Django Webapp
        run: |
          make ci-up
          cd ui && npm install
          cd ../clients/typescript && npm install && npm build
      - uses: cypress-io/github-action@v4.2.0
        with:
          start: npm run dev
          working-directory: ui
