name: Deploy UI
on:
  workflow_dispatch:

jobs:
  deploy:
    environment: live
    env:
      PRINTNANNY_API_URL: "https://api.printnanny.ai"
      GCP_SERVICE_ACCOUNT: ${{ secrets.PROD_GCP_SERVICE_ACCOUNT }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.PROD_GCP_SERVICE_ACCOUNT_KEY  }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Write deploy key
        run: echo $GCP_SERVICE_ACCOUNT_KEY > key.json
      - name: Active Service Account
        run: gcloud auth activate-service-account $GCP_SERVICE_ACCOUNT --key-file=key.json

      - name: Deploy UI
        id: deploy
        run: |
          make ui
          make ui-deploy
      - name: Invalidate Cache
        id: cache
        run: |
          gcloud config set project $GCP_PROJECT
          make ui-invalidate-cache
