# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  STRIPE_PORTAL_URL: ""
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mypy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # the following environment variables are for unit/e2e test mode only
    env:
      DATABASE_URL: "postgres://debug:debug@postgres:5432/print_nanny"
      COTURN_SECRET_KEY: testsecret1234
      COTURN_REALM: turn.test.com
      REDIS_URL: "redis://redis:6379/0"
      MAILGUN_API_KEY: ""
      MAILGUN_WEBHOOK_SIGNING_KEY: ""
      MAILGUN_DOMAIN: ""
      DISCORD_TOKEN: ""
      LOGLEVEL: debug
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Mypy
        shell: bash
        run: |
          pip3 install -r requirements/local.txt
          pip3 install -r requirements/test.txt
          mypy
  pylint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run black linter
        shell: bash
        run: |
          pip3 install -r requirements/test.txt
          make lint
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        run: |
          sudo apt install shellcheck
          make shellcheck
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Build UI
        run: |
          make ui
