name: Pytest and Cypress

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main, devel]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
  DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
  NKEYS_PATH: /var/lib/nats/nsc/keys
  NSC_HOME: /var/lib/nats/nsc
  NSC_STORE: /var/lib/nats/nsc/stores
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  STRIPE_TEST_PUBLIC_KEY: ${{ secrets.STRIPE_TEST_PUBLIC_KEY }}
  STRIPE_TEST_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}
  PRINTNANNY_WEBAPP_TAG: sha-${{ github.sha }}

# Docker Image cache from: https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
jobs:
  docker-image:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "us.gcr.io/print-nanny/print_nanny_webapp:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: compose/production/django/Dockerfile

  cypress:
    timeout-minutes: 20
    needs: docker-image
    environment: test
    env:
      # avoid warnings like "tput: No value for $TERM and no -T specified"
      TERM: xterm
      PRINTNANNY_WEBAPP_TAG: sha-${{ github.sha }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        browser:
          # Firefox doesn't support an equivalent of Chrome's --disable-web-security
          # so we're unable to test cross-origin requests between localhost and stripe.checkout.com
          # TODO find a way to enable/disable tests per platform
          # https://bugzilla.mozilla.org/show_bug.cgi?id=1039678
          # - "firefox"
          - "chrome"
          # - "edge"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install platform deps
        run: |
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install "edge"
        if: matrix.browser == 'edge'
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-stable.list'
          sudo rm microsoft.gpg
          sudo apt update
          sudo apt install microsoft-edge-stable
      - name: Cypres e2e
        run: |
          make ci-ui-test
          make ci-webapp
          cd ui && npm run test:e2e:ci -- --browser ${{ matrix.browser }}
  pytest:
    needs: docker-image
    environment: test

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Pytest
        env:
          PRINTNANNY_WEBAPP_TAG: sha-${{ github.sha }}
          STRIPE_PORTAL_URL: ${{ secrets.STRIPE_PORTAL_URL }}

        run: |
          make ci-pytest
